version: '2'

services:
  httpd:
    container_name: tasklist
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../../:/app/
    ports:
      - 80:80
    environment: 
      WEB_DOCUMENT_ROOT: "/app/laravel/public"
    links: 
      - db:db

  db:
    image: mariadb
    container_name: tasklist-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1212"