CREATE DATABASE IF NOT EXISTS `homestead`;
CREATE DATABASE IF NOT EXISTS `btg_ros`;
CREATE DATABASE IF NOT EXISTS `btg_ros_config`;
CREATE DATABASE IF NOT EXISTS `btg_ros_sales`;
CREATE DATABASE IF NOT EXISTS `btg_ros_tray`;